#docker build --tag esp-12e-alexa-door-bell-build --progress=plain ci/arduino
#docker run --interactive --tty --name esp-12e-alexa-door-bell-build-01 esp-12e-alexa-door-bell-build 
#docker start esp-12e-alexa-door-bell-build-01
#docker exec esp-12e-alexa-door-bell-build-01 actions-runner/run.sh #BE PATIENT
#docker stop esp-12e-alexa-door-bell-build-01

FROM solarbotics/arduino-cli-esp8266:2.0-0.25.0-python3.6





