#docker build --tag esp-12e-alexa-door-bell-build --progress=plain ci/arduino
#docker run --interactive --tty esp-12e-alexa-door-bell-build

FROM solarbotics/arduino-cli-esp8266:2.0-0.25.0-python3.6





