[*] --> ConnectWiFi


ConnectWiFi --> Sense: WiFi_is_connected / Print_connected

Sense --> Report: SwitchIsPushed / PrintSwitchIsPushed

Report : <<entry>> / NotifyAlexa

Report --> Sense : ReportSuccessful

